### ISSUE TITLE
Bug: Team Creation Broken

### ISSUE THREAD

**Issue by kraftmatic** [bmino/sparcPong#8]
Haven't had a chance to debug yet.  Just posting here for tracking purposes.  Fails out during the creation of a new team with the following stacktrace in the server log:

`Validating if player is a part of too many teams.
ReferenceError: reject is not defined
    at Object.verifyPlayerCanJoinById (/Users/nicholaskraftor/sparcPong/services/TeamService.js:31:28)
    at /Users/nicholaskraftor/sparcPong/routes/TeamController.js:29:45
    at Layer.handle [as handle_request] (/Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/layer.js:95:5)
    at /Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/index.js:317:13)
    at /Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nicholaskraftor/sparcPong/node_modules/express/lib/router/index.js:275:10)`

**Comment by bmino** [comment]
Fixed in commit "Properly Reject Promises when Creating Team" (6f952b652ebcae7703e77e57e461ac0cd8eae698)
